# -----------------------------
# NOTE: https://github.com/marketplace/actions/github-tag-bump
# example 2: on merge to master/main
# -----------------------------

name: 'Bump version [TEST]'

'on':
  push:
    branches:
      - dev

env:
  PATCH_WORDING: 'PATCH,patch,fix,hotfix,add'
  MINOR_WORDING: 'MINOR,minor,feat'
  MAJOR_WORDING: 'MAJOR,major,BREAKING'
  ACTIONS_RUNNER_DEBUG: true

# ðŸ”— read-more :|: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions: write-all

jobs:

  npm-version-bump:
    name: NPM Version Bump
    runs-on: ubuntu-22.04
    steps:

      - name: my-app-install token
        id: my-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.GH_APP_BOT }}

      - name: "STEP :|: checkout source code"
        uses: actions/checkout@v4
        with:
        # â–“ NOTE:
        # â–“ > âŒ [1]
        # â–“ > updating the use of the Personal Access Token (PAT) instead of the
        # â–“ > 'GITHUB_TOKEN' does not seem to be working.
        # env:
          # GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'
          # token: '${{ secrets.GH_TOKEN }}'
          token: '${{ steps.my-app.outputs.token }}'
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: 'dev'

      - name: "STEP :|: node config"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # â–“ NOTE:
      # â–“ > âŒ [1]
      # â–“ > changing the secret value for GH_ORG_NAME from 'CI Bot' to 'MigBash' did not
      # â–“ > work as intended, and permission error for the GitHub Action persists.
      - name: "STEP :|: git config"
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
          git config --global url.https://${{ steps.my-app.outputs.token }}@github.com/.insteadOf https://github.com/

      # â–“ NOTE:
      # â–“ > âŒ [1]
      # â–“ > using either 'GITHUB_TOKEN' or 'GH_TOKEN'
      # â–“ > gives the correct ADMIN permissions.
      # â–“ > ðŸ”— [2] :|: https://github.com/migbash/temp/actions/runs/7160175786/job/19494253126
      # â–“ > ðŸ”— [3] :|: https://github.com/migbash/temp/actions/runs/7160183755/job/19494270686
      - name: "CHECK :|: permissions check"
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          # GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' # [2]
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}' # [3]
      - name: Run only if user has sufficient permissions
        if: steps.check.outputs.has-permission
        run: echo "Congratulations! Your permissions to access the repository are sufficient."
      - name: Run only if user has NOT sufficient permissions
        if: "! steps.check.outputs.has-permission"
        run: echo "Sorry! Your permissions are insufficient."

      - name: git push version bump
        run: |
          # â–“ NOTE:
          # â–“ > ðŸŸ© correct secrets are retrived
          # â–“ > and are of the correct values.
          echo '${{ secrets.GH_ORG_NAME }}' | sed 's/./& /g'
          echo '${{ secrets.GH_ORG_EMAIL }}' | sed 's/./& /g'
          echo '${{ secrets.GH_TOKEN }}' | sed 's/./& /g'
          echo '${{ secrets.GITHUB_TOKEN }}' | sed 's/./& /g'
          echo '${{ steps.my-app.outputs.token }}' | sed 's/./& /g'

          # â–“ NOTE:
          # â–“ > testing new file persistance for github push.
          echo > text.txt
          git add .
          git commit -m "test"
          git push origin dev --follow-tags --force
        env:
          GITHUB_TOKEN: '${{ steps.my-app.outputs.token }}'
